// src/config/constants.js

export const WORLD = {
  width: 9000,
  height: 15000,
};

export const SKY = {
  near: 0x9fd6ff,
  high: 0x081327,
};

export const ALTITUDE = {
  mPerPx: 10,
  kmTroposphereTop: 12,
  kmStratosphereTop: 50,
  kmMesosphereTop: 85,
};

// --- NEW: Add this object for atmospheric physics ---
export const ATMOSPHERE = {
  // Standard sea-level temperature in Kelvin
  SEA_LEVEL_TEMP_K: 288.15, // 15°C
  
  // The rate at which temperature decreases with altitude in the troposphere (Kelvin per meter)
  // Standard lapse rate is ~6.5°C per km
  LAPSE_RATE_K_PER_M: 0.0065,

  // A base value for the lift generated by our helium, in Matter.js force units.
  // This represents the maximum lift at sea level.
  BASE_LIFT_FORCE: 0.00008
};